language: python
sudo: false

matrix:
  include:
    - python: "2.7"
      env: DEPS="numpy=1.9 scipy=0.16" BUILD_DOCS=false
    - python: "3.4"
      env: DEPS="numpy=1.9 scipy=0.16" BUILD_DOCS=false
    - python: "3.5"
      env: DEPS="numpy scipy" BUILD_DOCS=true


install:
  - conda update --yes conda
  - conda config --add channels soft-matter
  - conda create -n testenv --yes $DEPS pip nose setuptools python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - if [ $BUILD_DOCS == true ]; then pip install sphinx_bootstrap_theme; fi
  # for debugging...
  - echo $PATH
  - which python
  - conda info
  - conda list
  - python setup.py install

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

install:
  - pip install nose
  - pip install coverage
  - pip install codecov

script:
  - nosetests --nologcapture -a '!slow' --with-coverage --cover-package kombine

after_success:
  - coveralls --config_file .coveragerc
