language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install numpy
  - pip install nose
  - pip install coverage
  - pip install codecov

after_success:
  - coveralls --config_file .coveragerc
