language: python

python:
  - "2.6_with_system_site_packages"
  - "2.7_with_system_site_packages"
  - "3.3_with_system_site_packages"
  - "3.4_with_system_site_packages"
  - "3.5_with_system_site_packages"

before_install:
 - sudo apt-get update
 - sudo apt-get install python-scipy

install:
  - pip install numpy
  - pip install nose
  - pip install coverage
  - pip install codecov

script:
  - nosetests --with-coverage --cover-package kombine

after_success:
  - coveralls --config_file .coveragerc
