language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

before_install:
    - pip install codecov

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment --yes "python=$TRAVIS_PYTHON_VERSION"
  - source activate test-environment
  - python setup.py install

before_script:
  - pip install nose coverage

script:
  - nosetests --nologcapture -a '!slow' --with-coverage --cover-package kombine

after_success:
  - codecov
