language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get install -qq python-numpy python-scipy

install:
  - pip install nose
  - pip install coverage
  - pip install codecov

script:
  - nosetests --with-coverage --cover-package kombine

after_success:
  - coveralls --config_file .coveragerc
